### ISSUE TITLE
Code for 4.1 Private linear programming: DC optimal power flow (OPF) problem

### ISSUE THREAD

**Issue by guoyangqin** [wdvorkin/PrivateOpt#1]
It appears the code for Application 4.1 is not included in this repo. Could authors please kindly provide the corresponding code? It would be of great help for me to figure out the implementation detail of the chance-constrained LP. Thank you.

**Comment by wdvorkin** [comment]
Hi Guo, thanks for your interest. The code for Application 4.1. is included in this repo at [PrivateOpt](https://github.com/wdvorkin/PrivateOpt)/[casestudy](https://github.com/wdvorkin/PrivateOpt/tree/main/casestudy)/[OPF_ queries](https://github.com/wdvorkin/PrivateOpt/tree/main/casestudy/OPF_%20queries)
